name: License Plates
favicon: null
layout_spectrum: 0.9107344574294984
typography_spectrum: 0.5641114416066557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.01273875986225903
  lightness: 0.6019230440724641
  saturation: 0.5030486329924315
  rhythmicContrast: 0.9136740011163056
purpose: []
